<a href="https://colab.research.google.com/github/Shivaramkarthik/ML_24AG5A6618/blob/main/Numpay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 d array

In [1]:
import numpy as np

In [33]:
array1=[1,3,6,8,4]

In [3]:
array2=[5,4,7,4,8,9,10]

In [5]:
array3=[7,8,3,9,3]

In [32]:
print(array1)
print(array3)
print(array2)

[ 6  7  8 10 13]
[7, 8, 3, 9, 3]
[ 6  7  8 10 13]


In [34]:
array2D=[
    [1,3,4],
    [4,3,2],
    [5,46,7],
]
print(array2D[2][1])


46


In [35]:
array3D=  [
    [
        [1,5,7],
        [3,5,7]
        ],
        [
            [2,4,6],
            [4,6,7]
        ]
]
print(array3D[0][1][2])

7


In [36]:
array1 = np.array([1, 4, 6])
print(array1.dtype)

int64


In [18]:
array3D=  [
    [
        [1,5,7],
        [3,5,7]
        ],
        [
            [2,4,6],
            [4,6,7]
        ]
]
print(array3D)

[[[1, 5, 7], [3, 5, 7]], [[2, 4, 6], [4, 6, 7]]]


In [29]:
array1 = np.array(array1)
print(array1.size)

5


In [30]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])
print(array1.shape)

(2, 3)


In [31]:
array1 = np.array([6, 7, 8, 10, 13])
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)
print(array1.itemsize)
print(array2.itemsize)

8
4


In [37]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7c98d6163880>
Data of array2 is:  <memory at 0x7c98d5f90c70>


In [38]:
print(array1.ndim)

1


In [39]:
print(array1.size)

3


In [40]:
array1 = np.array([1, 3, 5, 7, 9])
print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


In [41]:
array1[1]=10
print(array1)

[ 1 10  5  7  9]


In [42]:
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])
element1 = array1[1, 3]
print("4th Element at 2nd Row:",element1)
element2 = array1[0, 1]
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


In [43]:
array1 = np.array([1, 2, 3, 4, 5])
median = np.median(array1)
print(median)

3.0


In [44]:
marks = np.array([76, 78, 81, 66, 85])
mean_marks = np.mean(marks)
print(mean_marks)

77.2


In [45]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.std(marks)
print(std_marks)

6.368673331236263


In [46]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.percentile(marks,50)
print(std_marks)


78.0


In [47]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.min(marks)
print(std_marks)


66


In [48]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.max(marks)
print(std_marks)

85
